Web_AMO_MVC/Models/BINHLUAN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_AMO_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public int IdBL { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayBinhLuan { get; set; }
        public string TrangThai { get; set; }
        public string UrlBaiViet { get; set; }
        public int IdBaiViet { get; set; }
        public int IdTaiKhoan { get; set; }
    
        public virtual BAIVIET BAIVIET { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}

Web_AMO_MVC/Areas/Admin/Controllers/BinhLuanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_AMO_MVC.Models;
using PagedList;
using PagedList.Mvc;
namespace Web_AMO_MVC.Areas.Admin.Controllers
{
    public class BinhLuanController : Controller
    {
        // GET: Admin/BinhLuan
        public ActionResult Index(int? page)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                int itemPageSize = 30;
                int pageNumber = (page ?? 1);
                var tatcabl = db.BINHLUANs.ToList();
                ViewBag.Count = tatcabl.Count;
                var dsbinhluan = db.BINHLUANs.OrderByDescending(n => n.NgayBinhLuan).ToPagedList(pageNumber, itemPageSize);
                ViewBag.IdTaiKhoan = new SelectList(db.TAIKHOANs.ToList(), "IdTK", "HoTen");
                ViewBag.IdBaiViet = new SelectList(db.BAIVIETs.ToList(), "IdBV", "TieuDe");
                return View(dsbinhluan);
            }
        }
        // POST: Admin/BinhLuan/Sua
        [HttpPost]
        public ActionResult Sua(BINHLUAN bl)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                BINHLUAN binhluan = db.BINHLUANs.SingleOrDefault(n => n.IdBL == bl.IdBL);
                if (binhluan != null)
                {
                    binhluan.TrangThai = bl.TrangThai;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
        //POST: Admin/BinhLuan/Xoa
        public ActionResult Xoa(int id)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                BINHLUAN bl = db.BINHLUANs.SingleOrDefault(n => n.IdBL == id);
                if (bl != null)
                {
                    db.BINHLUANs.Remove(bl);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
    }
}

Web_AMO_MVC/Areas/Admin/Views/BinhLuan/Index.cshtml
@model PagedList.PagedList<Web_AMO_MVC.Models.BINHLUAN>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Bình luận";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Danh sách bình luận bài viết</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                    </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                    <div class="table-responsive" style="margin-top:10px;">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Mã</th>
                                    <th>Nội dung bình luận</th>
                                    <th>Bình luận bài viết</th>
                                    <th>Trạng thái</th>
                                    <th>Ngày bình luận</th>
                                    <th>Người bình luận</th>
                                    <th style="text-align:center;">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var bl in Model)
                                    {
                                        <tr>
                                            <td>@bl.IdBL</td>
                                            <td>@Html.Raw(bl.NoiDung)</td>
                                            <td><a target="_blank" href="@bl.UrlBaiViet">@bl.BAIVIET.TieuDe</a></td>
                                            <td id="trangthai-@bl.IdBL">@bl.TrangThai</td>
                                            <td>@bl.NgayBinhLuan.Value.ToString("dd/MM/yyyy hh:mm tt")</td> <!--Chuyen kieu hien thi ngay thang nam dddd, dd/MM/yyyy hh:mm tt-->
                                            <td><span>@bl.TAIKHOAN.HoTen</span></td>
                                            <td>
                                                <div class="tools" style="text-align:center;">
                                                    <a data-toggle="modal" data-target="#modalSuaBinhLuan" onclick="LoadData(@bl.IdBL)"><i class="glyphicon glyphicon-edit" data-toggle="tooltip" title="Sửa"></i></a>
                                                    <a onclick="return confirm('Bạn có muốn xóa không?')" href="~/Admin/BinhLuan/Xoa/@bl.IdBL"><i class="glyphicon glyphicon-trash" data-toggle="tooltip" title="Xóa"></i></a>
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    Có tất cả: <span style="font-weight:bold"> @ViewBag.Count</span> bình luận <br />
    Trang: <span style="font-weight:bold"> @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount</span>
    @if (Model.PageCount <= 1)
    {
    }
    else
    {
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    }
</div>
<!-- Sửa -->
<script type="text/javascript">
    function LoadData(id) {
        $("#ma-bl").val(id);

        var trangThai = $("#trangthai-" + id + "").html();
        $("#trang-thai").val(trangThai);

    }
</script>


<!-- Modal Sửa-->
<div class="modal fade" id="modalSuaBinhLuan" role="dialog">
    <div class="modal-dialog modal-sm">
        @using (Html.BeginForm("Sua", "BinhLuan", FormMethod.Post))
            {
        <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Sửa tình trạng bình luận</h4>
                </div>
                <div class="modal-body">
                    <div class="box-body">
                        <div class="form-group" hidden>
                            <label>Mã bình luận</label>
                            <input type="text" class="form-control" id="ma-bl" name="IdBL" />
                        </div>

                        <div class="form-group">
                            <label>Tình trạng</label>
                            <select id="trang-thai" class="form-control" name="TrangThai">
                                <option value="Hiển thị">Hiển thị</option>
                                <option value="Ẩn">Ẩn</option>
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">Lưu</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Hủy bỏ</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>