Web_AMO_MVC/Models/PHONGBAN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_AMO_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONGBAN()
        {
            this.CANBOes = new HashSet<CANBO>();
        }
    
        public int IdPB { get; set; }
        public string TenPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANBO> CANBOes { get; set; }
    }
}

Web_AMO_MVC/Areas/Admin/Controllers/PhongBanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_AMO_MVC.Models;
namespace Web_AMO_MVC.Areas.Admin.Controllers
{
    public class PhongBanController : Controller
    {
        // GET: Admin/PhongBan
        [HttpGet]
        public ActionResult Index()
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                List<PHONGBAN> dsPhongban = db.PHONGBANs.ToList();
                return View(dsPhongban);
            }
        }
        // POST: Admin/PhongBan
        [HttpPost]
        public ActionResult Index(string tukhoa)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                List<PHONGBAN> lstResult = db.PHONGBANs.Where(n => n.TenPhong.Contains(tukhoa)).ToList();
                return View("Index", lstResult);
            }
        }

        // POST: Admin/PhongBan/Them
        [HttpPost]
        public ActionResult Them(PHONGBAN pb)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                //Kiểm tra tên phòng có trùng k?
                var checkTenPhong = db.PHONGBANs.SingleOrDefault(x => x.TenPhong.Trim() == pb.TenPhong.Trim());
                // không trùng thì thêm mới
                if (checkTenPhong == null)
                {
                    db.PHONGBANs.Add(pb);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
        // POST: Admin/PhongBan/Sua
        [HttpPost]
        public ActionResult Sua(PHONGBAN pb)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                PHONGBAN phongban = db.PHONGBANs.SingleOrDefault(n => n.IdPB == pb.IdPB);
                if (phongban != null)
                {
                    phongban.TenPhong = pb.TenPhong;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
        // POST: Admin/PhongBan/Xoa
        public ActionResult Xoa(int id)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                try
                {
                    PHONGBAN pb = db.PHONGBANs.SingleOrDefault(n => n.IdPB == id);
                    db.PHONGBANs.Remove(pb);
                    db.SaveChanges();
                }
                catch
                {

                }
                return RedirectToAction("Index");
            }
        }
    }
}

Web_AMO_MVC/Areas/Admin/Views/PhongBan/Index.cshtml
@{
    ViewBag.Title = "Phòng ban";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model List<Web_AMO_MVC.Models.PHONGBAN>

<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Danh sách phòng ban</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                    </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                    <div>
                        <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalThemPhongBan">Thêm</button>

                        <div class="navbar-right" style="margin-top:-10px;">
                            @using (Html.BeginForm("Index", "PhongBan", FormMethod.Post))
                            {
                                <div class="navbar-form" role="search">
                                    <div class="input-group">
                                        <input type="text" class="form-control" name="tukhoa" style="border-bottom-left-radius:3px;border-top-left-radius:3px" placeholder="Nhập từ khóa">
                                        <div class="input-group-btn">
                                            <button class="btn btn-default" id="btnsubmit" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <div class="table-responsive" style="margin-top:10px;">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th style="width:20px;"><input type="checkbox" id="ckbPbAll"></th>
                                    <th>Mã phòng ban</th>
                                    <th>Tên phòng ban</th>
                                    <th style="text-align:center;">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var phongban in Model)
                                {
                                    <tr>
                                        <td><input type="checkbox" class="ckbPb" name="idphongban" value="@phongban.IdPB"></td>
                                        <td>@phongban.IdPB</td>
                                        <td id="tenphongban-@phongban.IdPB">@phongban.TenPhong</td>
                                        <td>
                                            <div class="tools" style="text-align:center;">
                                                <a data-toggle="modal" data-target="#modalSuaPhongBan" onclick="LoadData(@phongban.IdPB)"><i class="glyphicon glyphicon-edit"></i></a>
                                                <a onclick="return confirm('Bạn có muốn xóa không?')" href="~/Admin/PhongBan/Xoa/@phongban.IdPB"><i class="glyphicon glyphicon-trash" data-toggle="tooltip" title="Delete"></i></a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--Checkbox-->
<script type="text/javascript">
        $(document).ready(function () {
            $('#ckbPbAll').click(function () {
                if ($(this).is(":checked"))
                    $('.ckbPb').prop('checked', true);
                else
                    $('.ckbPb').prop('checked', false);
            });
        });
    </script>

<!--Sửa-->
<script type="text/javascript">
    function LoadData(id) {
        $("#ma-pb").val(id);
        var tenPhongBan = $("#tenphongban-" + id + "").html();
        $("#ten-phong-ban").val(tenPhongBan);
    }
</script>



<!--Modal-->
<div class="modal fade" id="modalThemPhongBan" role="dialog">
    <div class="modal-dialog">
        @using (Html.BeginForm("Them", "PhongBan", FormMethod.Post))
        {
        <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Thêm mới phòng ban</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="box-body">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Tên phòng ban <label id="errtenphong"></label></label>
                                <div class="col-sm-9">
                                    <input type="text" id="txttenphong" class="form-control" name="TenPhong" placeholder="Nhập tên phòng ban">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="btnluu" class="btn btn-success">Lưu</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy bỏ</button>
                </div>
            </div>
        }
    </div>
</div>
<script type="text/javascript" language="javascript">
    $('#btnluu').click(function () {
        var error = 0;
        if ($('#txttenphong').val() == "") {
            $('#errtenphong').text("(*)");
            $('#errtenphong').css("color", "#FA5858");
            error++;
        }
        else {
            $('#errtenphong').text("");
            $('#errtenphong').css("color", "#666");
        }
        if (error != 0) {
            return false;
        }
        else
            return true;
    });
</script>
<!--Modal-->
<div class="modal fade" id="modalSuaPhongBan" role="dialog">
    <div class="modal-dialog">
        @using (Html.BeginForm("Sua", "PhongBan", FormMethod.Post))
        {
        <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Sửa phòng ban</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="box-body">
                            <div hidden class="form-group">
                                <label class="col-sm-3 control-label">Mã phòng ban</label>
                                <div class="col-sm-9">
                                    <input type="text" id="ma-pb" class="form-control" name="IdPB">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Tên phòng ban</label>
                                <div class="col-sm-9">
                                    <input type="text" id="ten-phong-ban" class="form-control" name="TenPhong">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">Lưu</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy bỏ</button>
                </div>
            </div>
        }
    </div>
</div>