Web_AMO_MVC/Models/VIDEO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_AMO_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO
    {
        public int IdVideo { get; set; }
        public string TenVideo { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string LinkVideo { get; set; }
        public Nullable<int> IdAlbum { get; set; }
        public Nullable<int> IdTaiKhoan { get; set; }
    
        public virtual ALBUM ALBUM { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}

Web_AMO_MVC/Areas/Admin/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_AMO_MVC.Models;
using PagedList;
using PagedList.Mvc;
namespace Web_AMO_MVC.Areas.Admin.Controllers
{
    public class VideoController : Controller
    {
        // GET: Admin/Video
        [HttpGet]
        public ActionResult Index(int? page)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                int itemPageSize = 20;
                int pageNumber = (page ?? 1);
                var tatcavideo = db.VIDEOs.ToList();
                ViewBag.Count = tatcavideo.Count;
                var dsvideo = db.VIDEOs.OrderByDescending(n => n.IdVideo).ToPagedList(pageNumber, itemPageSize);
                ViewBag.IdAlbum = new SelectList(db.ALBUMs.ToList(), "IdAlbum", "TenAlbum");
                ViewBag.IdTaiKhoan = new SelectList(db.TAIKHOANs.ToList(), "IdTK", "HoTen");
                return View(dsvideo);
            }
        }
        // POST: Admin/Video
        [HttpPost]
        public ActionResult Index(string tukhoa, int? page)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                int itemPageSize = 20;
                int pageNumber = (page ?? 1);
                var lstResult = db.VIDEOs.Where(n => n.TenVideo.Contains(tukhoa)).OrderByDescending(n => n.NgayDang).ToPagedList(pageNumber, itemPageSize);
                ViewBag.IdAlbum = new SelectList(db.ALBUMs.ToList(), "IdAlbum", "TenAlbum");
                ViewBag.IdTaiKhoan = new SelectList(db.TAIKHOANs.ToList(), "IdTK", "HoTen");
                return View("Index", lstResult);
            }
        }
        // POST: Admin/Video/Them
        public ActionResult Them(VIDEO vdo)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                if (vdo.NgayDang == null)
                {
                    vdo.NgayDang = DateTime.Parse(DateTime.Now.ToString());
                }
                else
                {
                    vdo.NgayDang = vdo.NgayDang;
                }
                db.VIDEOs.Add(vdo);
                ViewBag.IdAlbum = new SelectList(db.ALBUMs.ToList(), "IdAlbum", "TenAlbum");
                ViewBag.IdTaiKhoan = new SelectList(db.TAIKHOANs.ToList(), "IdTK", "HoTen");
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        // POST: Admin/Video/Sua
        public ActionResult Sua(VIDEO vdo)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                VIDEO video = db.VIDEOs.SingleOrDefault(n => n.IdVideo == vdo.IdVideo);
                if (video != null)
                {
                    video.TenVideo = vdo.TenVideo;
                    video.LinkVideo = vdo.LinkVideo;
                    if (vdo.NgayDang == null)
                    {
                        video.NgayDang = video.NgayDang;
                    }
                    else
                    {
                        video.NgayDang = vdo.NgayDang;
                    }
                    video.IdAlbum = vdo.IdAlbum;
                    ViewBag.IdAlbum = new SelectList(db.ALBUMs.ToList(), "IdAlbum", "TenAlbum", video.IdAlbum);
                    ViewBag.IdTaiKhoan = new SelectList(db.TAIKHOANs.ToList(), "IdTK", "HoTen");
                    video.IdTaiKhoan = vdo.IdTaiKhoan;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
        // POST: Admin/Video/Xoa
        public ActionResult Xoa(int id)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                VIDEO vdo = db.VIDEOs.SingleOrDefault(n => n.IdVideo == id);
                if (vdo != null)
                {
                    db.VIDEOs.Remove(vdo);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }
    }
}

Web_AMO_MVC/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_AMO_MVC.Models;
using PagedList;
using PagedList.Mvc;

namespace Web_AMO_MVC.Controllers
{
    public class VideoController : Controller
    {
        Web_KTCKEntities db = new Web_KTCKEntities();
        // GET: Video
        public ActionResult Index()
        {
            var album = db.ALBUMs;
            return View(album);
        }
        // GET: Video/ListVideo
        public ActionResult ListVideo(int? page, int id = 0)
        {
            int itemPageSize = 10;
            int pageNumber = (page ?? 1);
            var tatcavideo = db.VIDEOs.Where(n => n.IdAlbum == id).ToList();
            ViewBag.Count = tatcavideo.Count;
            var dsvideo = db.VIDEOs.Where(n => n.IdAlbum == id).OrderByDescending(n => n.NgayDang).ToPagedList(pageNumber, itemPageSize); ;
            return View(dsvideo);
        }
        // GET: Video/ChiTiet
        public ActionResult ChiTiet(int id = 0)
        {
            VIDEO video = db.VIDEOs.SingleOrDefault(n => n.IdVideo == id);
            if (video == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(video);
        }

        public PartialViewResult VideoTrongAlbum(int id)
        {
            var idalbum = db.VIDEOs.Find(id).IdAlbum;
            var videocungalbum = db.VIDEOs.Where(n => n.IdVideo != id && n.IdAlbum == idalbum).ToList();
            return PartialView(videocungalbum);
        }
    }
}

Web_AMO_MVC/Views/Video/ChiTiet.cshtml
@model Web_AMO_MVC.Models.VIDEO
@{
    ViewBag.Title = Model.TenVideo;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="well-sm" style="border:1px solid #d5d5d5; margin-bottom:1%;border-radius:unset">
    <a href="/">Trang chủ</a> >> <a href="/video">Album video</a> >> <a href="/danh-sach-video/@Model.IdAlbum/@Web_AMO_MVC.Models.ChuanHoaSEO.ConvertTitle(Model.ALBUM.TenAlbum)">@Model.ALBUM.TenAlbum</a> >> @Model.TenVideo
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12">
        <div>
            <iframe style="width:100%; height:350px;" src="@Model.LinkVideo" frameborder="0" allowfullscreen></iframe>
            <span style="font-weight:bold;color:#086ecf;font-size:28px;">
                @Model.TenVideo
            </span>
        </div>
    </div>
    <br />
</div>
<div>
    @Html.Action("VideoTrongAlbum", "Video", new List<Web_AMO_MVC.Models.VIDEO>())
</div>

Web_AMO_MVC/Views/Video/Index.cshtml
@model IEnumerable<Web_AMO_MVC.Models.ALBUM>
@{
    ViewBag.Title = "Album Video";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="well-sm" style="border:1px solid #d5d5d5; margin-bottom:1%;border-radius:unset">
    <a href="/">Trang chủ</a> >> <a href="/video">Album Video</a>
</div>

<div class="row">
    @if (Model != null)
    {
        foreach (var album in Model)
        {
            if (album.VIDEOs.Count > 0)
            {
                <div class="col-xs-6 col-sm-4">
                    <a href="/danh-sach-video/@album.IdAlbum/@Web_AMO_MVC.Models.ChuanHoaSEO.ConvertTitle(album.TenAlbum)">
                        <img class="img-responsive" style="height:140px;width:100%;border:1px solid #065ca5" src="@album.AnhDaiDien">
                    </a>
                    <div style="margin-top:6px;">
                        <a href="/danh-sach-video/@album.IdAlbum/@Web_AMO_MVC.Models.ChuanHoaSEO.ConvertTitle(album.TenAlbum)">
                            <label style="font-size:24px;color:#096be2">@album.TenAlbum</label>
                        </a>
                    </div>
                </div>
            }
        }
    }
</div>

Web_AMO_MVC/Views/Video/ListVideo.cshtml
@model PagedList.PagedList<Web_AMO_MVC.Models.VIDEO>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Danh sách video";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="well-sm" style="border:1px solid #d5d5d5; margin-bottom:1%;border-radius:unset">
    <a href="/">Trang chủ</a> >> <a href="/video">Album video</a> >> @foreach (var video in Model.Take(1))
    {
        @video.ALBUM.TenAlbum
    }
</div>

<div class="row">
    @if (Model != null)
    {
        foreach (var video in Model)
        {
            <div class="col-xs-12 col-sm-6">
                <iframe style="width:100%; height:250px;" src="@video.LinkVideo" frameborder="0" allowfullscreen></iframe>
                <span style="font-weight:bold;color:#086ecf;font-size:24px;color:#096be2"><a href="/Video/ChiTiet/@video.IdVideo">@video.TenVideo</a></span><br />
                <br />
            </div>
        }
    }
</div>

Có tất cả: <span style="font-weight:bold"> @ViewBag.Count</span> video trong album @foreach (var video in Model.Take(1))
{
    @video.ALBUM.TenAlbum
}
<br />


Trang: <span style="font-weight:bold"> @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount</span>
@if (Model.PageCount <= 1)
{
}
else
{
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
}

Web_AMO_MVC/Views/Video/VideoTrongAlbum.cshtml
@model List<Web_AMO_MVC.Models.VIDEO>

<div style="height:35px;line-height:35px;margin-bottom:2%; color:#fff;font-weight:bold;background:#1496C5;margin-top:3%">
    &nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-tasks"></span><label>  &nbsp;&nbsp;&nbsp; Video cùng Album </label>
</div>

<div class="row">
    @if (Model != null)
    {
        if (Model.Count > 0)
        {
            foreach (var videocungalbum in Model)
            {
                <div class="col-sm-3 col-xs-6">
                    <iframe style="width:100%;" src="@videocungalbum.LinkVideo" frameborder="0" allowfullscreen></iframe><br />
                    <span style="font-weight:bold;font-size:20px"><a style="color:#096be2" href="/Video/ChiTiet/@videocungalbum.IdVideo">@videocungalbum.TenVideo</a></span>
                    <br />
                </div>
            }
        }
        else
        {
            <div class="col-sm-12 col-xs-12">
                <span>Không có video nào cùng album</span>
            </div>
        }
    }
</div>
<br>