Web_AMO_MVC/Models/TAIKHOAN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_AMO_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.BAIVIETs = new HashSet<BAIVIET>();
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.CANBOes = new HashSet<CANBO>();
            this.HINHANHs = new HashSet<HINHANH>();
            this.LICHLAMVIECs = new HashSet<LICHLAMVIEC>();
            this.TAILIEUx = new HashSet<TAILIEU>();
            this.THONGBAOs = new HashSet<THONGBAO>();
            this.VIDEOs = new HashSet<VIDEO>();
        }
    
        public int IdTK { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string RetypePassword { get; set; }
        public string AnhDaiDien { get; set; }
        public string Quyen { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAIVIET> BAIVIETs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANBO> CANBOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANH> HINHANHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHLAMVIEC> LICHLAMVIECs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAILIEU> TAILIEUx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGBAO> THONGBAOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIDEO> VIDEOs { get; set; }
    }
}

Web_AMO_MVC/Areas/Admin/Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_AMO_MVC.Models;
using PagedList;
using PagedList.Mvc;
namespace Web_AMO_MVC.Areas.Admin.Controllers
{
    public class TaiKhoanController : Controller
    {
        // GET: Admin/TaiKhoan
        public ActionResult Index(string tukhoa, int? page)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                int itemPageSize = 20;
                int pageNumber = (page ?? 1);
                if (!String.IsNullOrEmpty(tukhoa))
                {
                    ViewBag.TuKhoa = tukhoa;
                    var lstResult = db.TAIKHOANs.Where(n => n.HoTen.Contains(tukhoa) || n.Email.Contains(tukhoa)).OrderByDescending(n => n.TrangThai).ToPagedList(pageNumber, itemPageSize);
                    return View("Index", lstResult);
                }
                else
                {
                    var tatcataikhoan = db.TAIKHOANs.ToList();
                    ViewBag.Count = tatcataikhoan.Count;
                    var dstaikhoan = db.TAIKHOANs.OrderBy(n => n.Quyen).ThenBy(n => n.TrangThai).ToPagedList(pageNumber, itemPageSize);
                    return View(dstaikhoan);

                }
            }
        }
        // POST: Admin/TaiKhoan/Sua
        public ActionResult Sua(TAIKHOAN tk)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                TAIKHOAN taikhoan = db.TAIKHOANs.SingleOrDefault(n => n.IdTK == tk.IdTK);
                taikhoan.HoTen = tk.HoTen;
                taikhoan.TrangThai = tk.TrangThai;
                taikhoan.Quyen = tk.Quyen;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        // GET: Admin/TaiKhoan/DangKy
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        // POST: Admin/TaiKhoan/DangKy
        [HttpPost]
        public ActionResult DangKy(TAIKHOAN tk)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                var checkMail = db.TAIKHOANs.SingleOrDefault(n => n.Email.Trim() == tk.Email.Trim());
                var checkTen = db.TAIKHOANs.SingleOrDefault(n => n.HoTen.Trim() == tk.HoTen.Trim());
                if (checkTen == null)
                {
                    if (checkMail == null)
                    {
                        tk.Password = MaHoaMd5.EncryptMD5(tk.Email + tk.Password);
                        tk.RetypePassword = MaHoaMd5.EncryptMD5(tk.Email + tk.RetypePassword);
                        tk.TrangThai = "Hoạt động";
                        tk.Quyen = "User";
                        db.TAIKHOANs.Add(tk);
                        db.SaveChanges();
                        ViewBag.tbDangKy = "Người dùng: " + tk.HoTen + " đăng ký thành công!";
                        return View();
                    }
                    else
                    {
                        ViewBag.tbTonTai = "Email: " + tk.Email + " đã tồn tại!";
                        return View();
                    }
                }
                else
                {
                    ViewBag.tbTonTai = "Tên người dùng: " + tk.HoTen + " đã tồn tại!";
                    return View();
                }
            }
        }

        // GET: Admin/TaiKhoan/DangNhap
        [HttpGet]
        public ActionResult DangNhap()
        {
            if (Request["returnUrl"] != null)
                Session["returnUrl"] = Request["returnUrl"];
            return View();
        }
        // POST: Admin/TaiKhoan/DangNhap
        [HttpPost]
        public ActionResult DangNhap(TAIKHOAN tk)
        {
            using (Web_KTCKEntities db = new Web_KTCKEntities())
            {
                tk.Password = MaHoaMd5.EncryptMD5(tk.Email + tk.Password);
                var checkTKAdmin = db.TAIKHOANs.SingleOrDefault(n => n.Email.Trim().Equals(tk.Email) && n.Password.Trim().Equals(tk.Password) && n.Quyen.Equals("Admin") && n.TrangThai.Equals("Hoạt động"));
                if (checkTKAdmin != null)
                {
                    Session["IdTK"] = checkTKAdmin.IdTK.ToString();
                    Session["HoTen"] = checkTKAdmin.HoTen.ToString();
                    Session["Email"] = checkTKAdmin.Email.ToString();
                    Session["Quyen"] = "Admin";
                    Session["AnhDaiDien"] = checkTKAdmin.AnhDaiDien.ToString();
                    return Redirect("/Admin/Home/Index");
                }
                var checkTKUser = db.TAIKHOANs.SingleOrDefault(n => n.Email.Trim().Equals(tk.Email) && n.Password.Trim().Equals(tk.Password) && n.Quyen.Equals("User") && n.TrangThai.Equals("Hoạt động"));
                if (checkTKUser != null)
                {
                    Session["IdTK"] = checkTKUser.IdTK.ToString();
                    Session["HoTen"] = checkTKUser.HoTen.ToString();
                    Session["Quyen"] = "User";
                    if (Session["returnUrl"] == null)
                        return Redirect("/Home/Index");
                    else
                        return Redirect(Session["returnUrl"].ToString());
                }
                else
                {
                    ViewBag.tbDangNhap = "Email, mật khẩu sai hoặc tài khoản đã bị khóa";
                    return View();
                }

            }
        }

        // Admin/TaiKhoan/DangXuat
        public void DangXuat()
        {
            Session.Clear();
            Session["IdTK"] = null;
            Session["HoTen"] = null;
            Session["Email"] = null;
            Session["AnhDaiDien"] = null;
            Response.Redirect("~/Home/Index");
        }
    }
}

Web_AMO_MVC/Areas/Admin/Views/TaiKhoan/DangKy.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Đăng ký tài khoản</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="~/Areas/Admin/Content/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Areas/Admin/Content/dist/css/AdminLTE.min.css">
</head>
<body class="hold-transition register-page">
    <div class="register-box">
        <div class="register-box-body">
            <p class="register-logo" style="font-size:20px; font-weight:bold">Đăng ký tài khoản</p>
            @if (ViewBag.tbDangKy != null)
            {
                <label style="color:#09c4a8">@ViewBag.tbDangKy</label>
            }
            @if (ViewBag.tbTonTai != null)
            {
                <label style="color:#FA5858">@ViewBag.tbTonTai</label>
            }
            @using (Html.BeginForm("DangKy", "TaiKhoan", FormMethod.Post))
            {
                <div class="form-group has-feedback">
                    <label>Tên người dùng</label> <label id="errorten"></label>
                    <input type="text" class="form-control" name="HoTen" id="txtten" placeholder="Nhập tên người dùng">
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <label>Email</label> <label id="erroremail"></label>
                    <input type="email" class="form-control" name="Email" id="txtemail" placeholder="Nhập email của bạn">
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <label>Mật khẩu</label> <label id="errorpass"></label>
                    <input type="password" class="form-control" name="Password" id="txtmatkhau" placeholder="Nhập mật khẩu của bạn">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <label>Nhập lại mật khẩu</label> <label id="errorrepass"></label>
                    <input type="password" class="form-control" name="RetypePassword" id="txtlaimatkhau" placeholder="Nhập lại mật khẩu của bạn">
                    <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>
                <div hidden class="form-group has-feedback">
                    <label>Ảnh đại diên</label> <label id="errorrepass"></label>
                    <input type="text" class="form-control" name="AnhDaiDien" value="~/Areas/Admin/Content/dist/img/avatar.png">
                    <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>
                <div class="row" style="margin-bottom:2%">
                    <div class="col-xs-12">
                        <button type="submit" id="btnsubmit" class="btn btn-md btn-primary btn-block">Đăng ký</button>
                    </div>
                </div>
                <label> Bạn muốn quay về?</label><a href="/"> Trang chủ</a><br />
                <label> Bạn đã có tài khoản? </label><a href="~/Admin/dang-nhap"> Đăng nhập</a>
            }
        </div>
    </div>
    <!-- jQuery 2.2.3 -->
    <script src="~/Areas/Admin/Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="~/Areas/Admin/Content/bootstrap/js/bootstrap.min.js"></script>

    <script type="text/javascript">
        $('#btnsubmit').click(function () {
            var error = 0;
            if ($('#txtten').val() == "") {
                $('#errorten').text("(*)");
                $('#errorten').css("color", "#FA5858");
                error++;
            }
            else {
                $('#errorten').text("");
                $('#errorten').css("color", "#666");
            }

            if ($('#txtemail').val() == "") {
                $('#erroremail').text("(*)");
                $('#erroremail').css("color", "#FA5858");
                error++;
            }
            else {
                $('#erroremail').text("");
                $('#erroremail').css("color", "#666");
            }

            if ($('#txtmatkhau').val() == "") {
                $('#errorpass').text("(*)");
                $('#errorpass').css("color", "#FA5858");
                error++;
            }
            else {
                $('#errorpass').text("");
                $('#errorpass').css("color", "#666");
            }

            if ($('#txtlaimatkhau').val() == "") {
                $('#errorrepass').text("(*)");
                $('#errorrepass').css("color", "#FA5858");
                error++;
            }
            else if ($('#txtmatkhau').val() != $('#txtlaimatkhau').val()) {
                $('#errorrepass').text("(**)");
                $('#errorrepass').css("color", "#FA5858");
                error++;
            }
            else {
                $('#errorrepass').text("");
                $('#errorrepass').css("color", "#666");
            }

            if (error != 0) {
                return false;
            }
            else
                return true;
        });
    </script>
</body>
</html>
<noembed>

Web_AMO_MVC/Areas/Admin/Views/TaiKhoan/DangNhap.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Đăng nhập tài khoản</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="~/Areas/Admin/Content/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Areas/Admin/Content/dist/css/AdminLTE.min.css">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-box-body">
            <p class="login-logo" style="font-size:20px; font-weight:bold">Đăng nhập tài khoản</p>
            @if (@ViewBag.tbDangNhap != null)
            {
                <label style="color:#FA5858;">@ViewBag.tbDangNhap</label>
            }
            @using (Html.BeginForm("DangNhap", "TaiKhoan", FormMethod.Post))
            {
                <div class="form-group has-feedback">
                    <label>Email</label> <label id="erroremail"></label>
                    <input type="email" name="Email" id="txtemail" class="form-control" placeholder="Nhập email của bạn">
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <label>Mật khẩu</label> <label id="errorpassword"></label>
                    <input type="password" id="txtpassword" name="Password" class="form-control" placeholder="Nhập mật khẩu của bạn">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row" style="margin-bottom:2%">
                    <div class="col-xs-12">
                        <button type="submit" id="btnsubmit" class="btn btn-md btn-primary btn-block">Đăng nhập</button>
                    </div>
                </div>
                <label> Bạn muốn quay về?</label><a href="/"> Trang chủ</a><br />
                <label> Bạn chưa có tài khoản? </label><a href="~/Admin/dang-ky"> Đăng ký</a>
            }
        </div>
    </div>
    <!-- jQuery 2.2.3 -->
    <script src="~/Areas/Admin/Content/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="~/Areas/Admin/Content/bootstrap/js/bootstrap.min.js"></script>

    <script type="text/javascript">
        $('#btnsubmit').click(function () {
            var error = 0;
            if ($('#txtemail').val() == "") {
                $('#erroremail').text("(*)");
                $('#erroremail').css("color", "#FA5858");
                error++;
            }
            else {
                $('#erroremail').text("");
                $('#erroremail').css("color", "#666");
            }

            if ($('#txtpassword').val() == "") {
                $('#errorpassword').text("(*)");
                $('#errorpassword').css("color", "#FA5858");
                error++;
            }
            else {
                $('#errorpassword').text("");
                $('#errorpassword').css("color", "#666");
            }
            if (error != 0) {
                return false;
            }
            else
                return true;
        });
    </script>
</body>
</html>
<noembed>

Web_AMO_MVC/Areas/Admin/Views/TaiKhoan/Index.cshtml
@model PagedList.PagedList<Web_AMO_MVC.Models.TAIKHOAN>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Tài khoản";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Danh sách tài khoản</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                    </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                    <div>
                        <div class="navbar-right" style="margin-top:-10px;">
                            @using (Html.BeginForm("Index", "TaiKhoan", FormMethod.Get))
                            {
                                <div class="navbar-form" role="search">
                                    <div class="input-group">
                                        <input type="text" class="form-control" name="tukhoa" style="border-bottom-left-radius:3px;border-top-left-radius:3px" placeholder="Nhập từ khóa">
                                        <div class="input-group-btn">
                                            <button class="btn btn-default" id="btnsubmit" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>

                    </div>
                    <div class="table-responsive" style="margin-top:40px;">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Mã tài khoản</th>
                                    <th>Họ tên</th>
                                    <th>Email</th>
                                    <th>Ảnh đại diện</th>
                                    <th>Quyền</th>
                                    <th>Trạng thái</th>
                                    <th style="text-align:center;">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var tk in Model)
                                    {
                                        <tr>
                                            <td>@tk.IdTK</td>
                                            <td id="hoten-@tk.IdTK">@tk.HoTen</td>
                                            <td>@tk.Email</td>
                                            <td><img src="@tk.AnhDaiDien" style="max-width:50px; max-height:50px" /></td>
                                            <td id="quyen-@tk.IdTK">@tk.Quyen</td>
                                            <td id="trangthai-@tk.IdTK">@tk.TrangThai</td>
                                            <td>
                                                <div class="tools" style="text-align:center;">
                                                    <a data-toggle="modal" data-target="#modalSuaTK" onclick="LoadData(@tk.IdTK)"><i class="glyphicon glyphicon-edit" data-toggle="tooltip" title="Sửa"></i></a>
                                                    @* <a onclick="return confirm('Bạn có muốn xóa không?')" href="~/Admin/TaiKhoan/Xoa/@tk.IdTK"><i class="glyphicon glyphicon-trash" data-toggle="tooltip" title="Xóa"></i></a>*@
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    Có tất cả: <span style="font-weight:bold"> @ViewBag.Count</span> tài khoản <br />
    Trang: <span style="font-weight:bold"> @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount</span>
    @if (Model.PageCount <= 1)
    {
    }
    else
    {
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, @tukhoa = @ViewBag.Tukhoa }))
    }
</div>


<script type="text/javascript">
    function LoadData(id) {
        $("#ma-tk").val(id);
        var hoTen = $("#hoten-" + id + "").html();
        $("#ho-ten").val(hoTen);
        var quyen = $("#quyen-" + id + "").html();
        $("#quyen").val(quyen);
        var trangThai = $("#trangthai-" + id + "").html();
        $("#trang-thai").val(trangThai);
    }
</script>

<!-- Modal -->
<div class="modal fade" id="modalSuaTK" role="dialog">
    <div class="modal-dialog">
        @using (Html.BeginForm("Sua", "TaiKhoan", FormMethod.Post))
        {
        <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Sửa tài khoản</h4>
                </div>
                <div class="modal-body">
                    <div hidden class="form-group">
                        <label>Mã tài khoản</label>
                        <input type="text" class="form-control" id="ma-tk" name="IdTK" />
                    </div>
                    <div class="form-group">
                        <label>Họ tên</label>
                        <input type="text" class="form-control" id="ho-ten" name="HoTen" />
                    </div>
                    <div class="form-group">
                        <label>Quyền</label>
                        <select class="form-control" id="quyen" name="Quyen">
                            <option value="User">User</option>
                            <option value="Admin">Admin</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Trạng thái</label>
                        <select class="form-control" id="trang-thai" name="TrangThai">
                            <option value="Hoạt động">Hoạt động</option>
                            <option value="Vô hiệu hóa">Vô hiệu hóa</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">Lưu</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy bỏ</button>
                </div>
            </div>
        }
    </div>
</div>